# Generated by Django 3.1.5 on 2021-03-27 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('course_image', models.ImageField(default='', upload_to='course-images/')),
                ('desc', models.CharField(default='', max_length=250)),
            ],
            options={
                'ordering': ['course_name'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lec_id', models.AutoField(primary_key=True, serialize=False)),
                ('lec_no', models.CharField(default='0', max_length=100)),
                ('lecture_name', models.CharField(default='', max_length=100)),
                ('lec_date', models.DateField(auto_now=True)),
                ('video', models.FileField(null=True, upload_to='videos/')),
                ('material', models.FileField(null=True, upload_to='lec_materials/')),
                ('thumbnail', models.ImageField(default='', upload_to='course-images/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(default='', max_length=10)),
                ('password', models.CharField(default='', max_length=10)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone_no', models.CharField(default='', max_length=20)),
                ('image', models.ImageField(default='', upload_to='course-images/')),
                ('dob', models.DateField(auto_now=True)),
                ('stud_category', models.CharField(choices=[('U', 'Under Grad'), ('P', 'Post Grad'), ('H', 'High School Student'), ('O', 'Others')], default='U', max_length=2, null=True)),
                ('courses', models.ManyToManyField(to='accounts.Course')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Watch_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateField(auto_now=True)),
                ('Rating', models.IntegerField(default=0)),
                ('student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('w_lect', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=100)),
                ('username', models.CharField(default='', max_length=10)),
                ('password', models.CharField(default='', max_length=10)),
                ('teacher_image', models.ImageField(default='', upload_to='teacher-images/')),
                ('teacher_email', models.EmailField(default='', max_length=254)),
                ('teacher_phone', models.CharField(default='', max_length=20)),
                ('teacher_dob', models.DateField()),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.course')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher'),
        ),
    ]
