# Generated by Django 3.1.3 on 2021-05-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('edit_time', models.DateField()),
            ],
        ),
    ]
